.TH wast 1 wast\-VERSION
.SH NAME
wast \- wall fast
.SH SYNOPSIS
.B wast
.RB [ \-v ]
.RI [ image ]
.P
.SH DESCRIPTION
.B wast
reads an image and outputs all the 'relevant' colors that are found. You may
find out that the colors outputed are not 'all' the colors on the image. This
is because if the image is larger than 'maxsize' (default 512) it will resize
the image making the execution time much faster (since we have less pixel to
look for) and removes colors that are not repeated that much ('irrelevant
colors').
.P
.SH OPTIONS
.B \-v
prints version information to stdout, then exits.
.SH SEE ALSO
.IR wal
